/********************************************************************
 *    $Id$
 *********************************************************************/
#ifndef _FSSRWR_H
#define _FSSRWR_H

VOID RegisterFSSR(VOID);

VOID UnRegisterFSSR(VOID);
INT4 FsSrModeGet(tSnmpIndex *, tRetVal *);
INT4 FsSrV4MinSrGbValueGet(tSnmpIndex *, tRetVal *);
INT4 FsSrV4MaxSrGbValueGet(tSnmpIndex *, tRetVal *);
INT4 FsSrModeSet(tSnmpIndex *, tRetVal *);
INT4 FsSrV4MinSrGbValueSet(tSnmpIndex *, tRetVal *);
INT4 FsSrV4MaxSrGbValueSet(tSnmpIndex *, tRetVal *);
INT4 FsSrModeTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrV4MinSrGbValueTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrV4MaxSrGbValueTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrModeDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrV4MinSrGbValueDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrV4MaxSrGbValueDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 GetNextIndexFsSrSIDTable(tSnmpIndex *, tSnmpIndex *);
INT4 FsSrSIDTypeGet(tSnmpIndex *, tRetVal *);
INT4 FsSrSidIndexTypeGet(tSnmpIndex *, tRetVal *);
INT4 FsSrSIDValueGet(tSnmpIndex *, tRetVal *);
INT4 FsSrFlagsGet(tSnmpIndex *, tRetVal *);
INT4 FsSrMTIDGet(tSnmpIndex *, tRetVal *);
INT4 FsSrAlgoGet(tSnmpIndex *, tRetVal *);
INT4 FsSrWeightGet(tSnmpIndex *, tRetVal *);
INT4 FsSrSIDRowStatusGet(tSnmpIndex *, tRetVal *);
INT4 FsSrSIDTypeSet(tSnmpIndex *, tRetVal *);
INT4 FsSrSidIndexTypeSet(tSnmpIndex *, tRetVal *);
INT4 FsSrSIDValueSet(tSnmpIndex *, tRetVal *);
INT4 FsSrFlagsSet(tSnmpIndex *, tRetVal *);
INT4 FsSrMTIDSet(tSnmpIndex *, tRetVal *);
INT4 FsSrAlgoSet(tSnmpIndex *, tRetVal *);
INT4 FsSrWeightSet(tSnmpIndex *, tRetVal *);
INT4 FsSrSIDRowStatusSet(tSnmpIndex *, tRetVal *);
INT4 FsSrSIDTypeTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrSidIndexTypeTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrSIDValueTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrFlagsTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrMTIDTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrAlgoTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrWeightTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrSIDRowStatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrSIDTableDep(UINT4 *, tSnmpIndexList*, tSNMP_VAR_BIND*);
INT4 FsSrDebugFlagGet(tSnmpIndex *, tRetVal *);
INT4 FsRouterListIndexNextGet(tSnmpIndex *, tRetVal *);
INT4 FsSrDebugFlagSet(tSnmpIndex *, tRetVal *);
INT4 FsSrDebugFlagTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrDebugFlagDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 GetNextIndexFsSrTePathTable(tSnmpIndex *, tSnmpIndex *);
INT4 FsSrTeRouterListIndexGet(tSnmpIndex *, tRetVal *);
INT4 FsSrTePathRowStatusGet(tSnmpIndex *, tRetVal *);
INT4 FsSrTeRouterListIndexSet(tSnmpIndex *, tRetVal *);
INT4 FsSrTePathRowStatusSet(tSnmpIndex *, tRetVal *);
INT4 FsSrTeRouterListIndexTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrTePathRowStatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrTePathTableDep(UINT4 *, tSnmpIndexList*, tSNMP_VAR_BIND*);
INT4 GetNextIndexFsSrTeRtrListTable(tSnmpIndex *, tSnmpIndex *);
INT4 FsSrTeOptRouterIdGet(tSnmpIndex *, tRetVal *);
INT4 FsSrTeRtrRowStatusGet(tSnmpIndex *, tRetVal *);
INT4 FsSrTeOptRtrAddrTypeSet(tSnmpIndex *, tRetVal *);
INT4 FsSrTeOptRouterIdSet(tSnmpIndex *, tRetVal *);
INT4 FsSrTeRtrRowStatusSet(tSnmpIndex *, tRetVal *);
INT4 FsSrTeOptRtrAddrTypeTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrTeOptRouterIdTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrTeRtrRowStatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrTeRtrListTableDep(UINT4 *, tSnmpIndexList*, tSNMP_VAR_BIND*);
INT4 FsSrV4StatusGet(tSnmpIndex *, tRetVal *);
INT4 FsSrV4AlternateStatusGet(tSnmpIndex *, tRetVal *);
INT4 FsSrV6MinSrGbValueGet(tSnmpIndex *, tRetVal *);
INT4 FsSrV6MaxSrGbValueGet(tSnmpIndex *, tRetVal *);
INT4 FsSrV6AlternateStatusGet(tSnmpIndex *, tRetVal *);
INT4 FsSrV6StatusGet(tSnmpIndex *, tRetVal *);
INT4 FsSrGlobalAdminStatusGet(tSnmpIndex *, tRetVal *);
INT4 FsSrIpv4AddrFamilyGet(tSnmpIndex *, tRetVal *);
INT4 FsSrIpv6AddrFamilyGet(tSnmpIndex *, tRetVal *);
INT4 FsSrV4StatusSet(tSnmpIndex *, tRetVal *);
INT4 FsSrV4AlternateStatusSet(tSnmpIndex *, tRetVal *);
INT4 FsSrV6MinSrGbValueSet(tSnmpIndex *, tRetVal *);
INT4 FsSrV6MaxSrGbValueSet(tSnmpIndex *, tRetVal *);
INT4 FsSrV6AlternateStatusSet(tSnmpIndex *, tRetVal *);
INT4 FsSrV6StatusSet(tSnmpIndex *, tRetVal *);
INT4 FsSrGlobalAdminStatusSet(tSnmpIndex *, tRetVal *);
INT4 FsSrIpv4AddrFamilySet(tSnmpIndex *, tRetVal *);
INT4 FsSrIpv6AddrFamilySet(tSnmpIndex *, tRetVal *);
INT4 FsSrV4StatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrV4AlternateStatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrV6MinSrGbValueTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrV6MaxSrGbValueTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrV6AlternateStatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrV6StatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrGlobalAdminStatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrIpv4AddrFamilyTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrIpv6AddrFamilyTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsSrV4StatusDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrV4AlternateStatusDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrV6MinSrGbValueDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrV6MaxSrGbValueDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrV6AlternateStatusDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrV6StatusDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrGlobalAdminStatusDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrIpv4AddrFamilyDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 FsSrIpv6AddrFamilyDep(UINT4 *, tSnmpIndexList *, tSNMP_VAR_BIND *);
INT4 GetNextIndexFsStaticSrLabelStackTable(tSnmpIndex *, tSnmpIndex *);
INT4 FsStaticSrLabelStackLabelGet(tSnmpIndex *, tRetVal *);
INT4 FsStaticSrLabelStackLabelSet(tSnmpIndex *, tRetVal *);
INT4 FsStaticSrLabelStackLabelTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsStaticSrLabelStackTableDep(UINT4 *, tSnmpIndexList*, tSNMP_VAR_BIND*);
INT4 GetNextIndexFsStaticSrTable(tSnmpIndex *, tSnmpIndex *);
INT4 FsStaticSrNextHopAddrGet(tSnmpIndex *, tRetVal *);
INT4 FsStaticSrLabelStackIndexGet(tSnmpIndex *, tRetVal *);
INT4 FsStaticSrRowStatusGet(tSnmpIndex *, tRetVal *);
INT4 FsStaticSrNextHopAddrSet(tSnmpIndex *, tRetVal *);
INT4 FsStaticSrLabelStackIndexSet(tSnmpIndex *, tRetVal *);
INT4 FsStaticSrRowStatusSet(tSnmpIndex *, tRetVal *);
INT4 FsStaticSrNextHopAddrTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsStaticSrLabelStackIndexTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsStaticSrRowStatusTest(UINT4 *, tSnmpIndex *, tRetVal *);
INT4 FsStaticSrTableDep(UINT4 *, tSnmpIndexList*, tSNMP_VAR_BIND*);
INT4 FsLabelStackIndexNextGet(tSnmpIndex *, tRetVal *);
#endif /* _FSSRWR_H */
